CREATE OR REPLACE PROCEDURE inserimentoCliente (
	CF_CLI IN  VARCHAR2,	-- CODICE PRODOTTO EQUIPAGGIAMENTO
	NOME IN  VARCHAR2,		-- NOME CLIENTE
	COGNOME IN  VARCHAR2,	-- COGNOME CLIENTE
	DATA_N IN  DATE,	-- D.N. CLIENTE
	VIA IN  VARCHAR2,	-- VIA CLIENTE
	CAP IN NUMBER,      -- CAP CLIENTE
	CITTA IN VARCHAR2,  -- CITTA CLIENTE
	NUM_PORTO_AR IN VARCHAR2,  --NUM. PORTO ARMI CLIENTE
	TEL IN VARCHAR2            --TEL. CLIENTE
	)
	AS
	BEGIN
	INSERT INTO PERSONA (CF,NOME,COGNOME,DATA_NASCITA,VIA,CAP,CITTA)
	VALUES	(CF_CLI, NOME, COGNOME, DATA_N, VIA, CAP, CITTA);
	
	INSERT INTO CLIENTE (NUM_PORTO_ARMI,CF_CLI,TELEFONO)
	VALUES(NUM_PORTO_AR, CF_CLI, TEL);
	END;
	/