CREATE OR REPLACE PROCEDURE inserimentoArma (
	COD_PR IN  VARCHAR2,	-- CODICE PRODOTTO EQUIPAGGIAMENTO
	CAL IN  NUMBER,		-- CALIBRO ARMA
	MAR IN  VARCHAR2,	-- MARCA
	COD_FORNITURA IN  VARCHAR2,	-- CODICE FORNITURA
	MATRIS IN  VARCHAR2,	-- MATRICOLA ARMA
	MODEL IN  VARCHAR2		-- MODELLO ARMA
	)
	AS
	BEGIN
	INSERT INTO EQUIPAGGIAMENTO (CODICE_PRODOTTO, CALIBRO, MARCA, COD_FORNITURA)
	VALUES	(COD_PR, CAL, MAR, COD_FORNITURA);
	
	INSERT INTO ARMA (MATRICOLA,MODELLO,CODICE_PRODOTTO)
	VALUES(MATRIS, MODEL, COD_PR);
	END;
	/
	