CREATE OR REPLACE PROCEDURE inserimentoMunizioni (
	COD_PR IN  VARCHAR2,	-- CODICE PRODOTTO EQUIPAGGIAMENTO
	CAL IN  NUMBER,		-- CALIBRO ARMA
	MAR IN  VARCHAR2,	-- MARCA
	COD_FORNITURA IN  VARCHAR2,	-- CODICE FORNITURA
	NUM IN  VARCHAR2	-- NUM_LOTTO MUNIZIONI
	)
	AS
	BEGIN
	INSERT INTO EQUIPAGGIAMENTO (CODICE_PRODOTTO, CALIBRO, MARCA, COD_FORNITURA)
	VALUES	(COD_PR, CAL, MAR, COD_FORNITURA);
	
	INSERT INTO MUNIZIONI (NUM_LOTTO,CODICE_PRODOTTO)
	VALUES(NUM, COD_PR);
	END;
	/
	