-- RIPULISCE DB
DROP TABLE COMMISSARIATO;
DROP TABLE DENUNCIA;
DROP TABLE DENUNCIA_ARMA;
DROP TABLE DENUNCIA_MUNIZIONI;
DROP TABLE DIPENDENTE;
DROP TABLE TURNI_PROGRAMMATI;
DROP TABLE TURNI_EFFETTUATI;
DROP TABLE VENDITA;
DROP TABLE EQUIPAGGIAMENTO;
DROP TABLE ARMA;
DROP TABLE MUNIZIONI;
DROP TABLE ACCESSORIO;
DROP TABLE CONTIENE;
DROP TABLE FORNITURA;
DROP TABLE FORNITORE;
DROP TABLE VENDUTO;
DROP TABLE CLIENTE;

-- CREAZIONE TABELLE
CREATE TABLE COMMISSARIATO(
	PEC			VARCHAR2(50) PRIMARY KEY,
	NOME_COMM	VARCHAR2(50),
	CAP			NUMBER(5),
	VIA			VARCHAR(40),
	CITTA		VARCHAR(20),
);

CREATE TABLE DENUNCIA(
	CODICE_PROGRESSIVO	NUMBER(10) PRIMARY KEY,
	DATA_DENUNCIA		DATE
	PEC					VARCHAR2(50) FOREIGN KEY,
	CF					VARCHAR2(16) FOREIGN KEY,
	MATRICOLA			VARCHAR2(7) FOREIGN KEY,
);

CREATE TABLE DENUNCIA_ARMA
	
);

CREATE TABLE DENUNCIA_MUNIZIONI(
	CODICE_PROGRESSIVO	NUMBER(10) FOREIGN KEY,
	TIPO				VARCHAR2(8),
	NUM_PEZZI			NUMBER(4),
);

CREATE TABLE DIPENDENTE(
	CF_DIP		VARCHAR2(16) PRIMARY KEY,
	TELEFONO	NUMBER(10),
	NOME		VARCHAR2(30),
	COGNOME		VARCHAR2(30),
);

CREATE TABLE TURNI_PROGRAMMATI(
	DATA_TP		DATE PRIMARY KEY,
	ORA_TP		TIME PRIMARY KEY,
	CF_DIP		VARCHAR2(16) FOREIGN KEY,
);

CREATE TABLE TURNI_EFFETTUATI(
	DATA_TE		DATE PRIMARY KEY,
	ORA_TE		TIME PRIMARY KEY,
	CF_DIP		VARCHAR2(16) FOREIGN KEY,
);	

CREATE TABLE VENDITA(
	NUM_PROG	NUMBER(10) PRIMARY KEY,
	DATA_V		DATE,
	ORA_V		TIME,
	IMPORTO		NUMBER(19,4),
	CF_DIP		VARCHAR2(16) FOREIGN KEY,
);

CREATE TABLE EQUIPAGGIAMENTO(
	MATRICOLA		VARCHAR2(7) PRIMARY KEY,
	CALIBRO			NUMBER(2),
	MARCA			VARCHAR2(20),
	COD_FORNITURA	NUMBER(10) FOREIGN KEY,
	CF_CLIENTE		VARCHAR2(16) FOREIGN KEY,
	NUM_PROG		NUMBER(10) FOREIGN KEY,
);

CREATE TABLE ARMA(
	MODELLO 	VARCHAR2(20),
	MATRICOLA	VARCHAR2(7) FOREIGN KEY,
);

CREATE TABLE MUNIZIONI(
	NUM_LOTTO	NUMBER(10),
	MATRICOLA	VARCHAR2(7) FOREIGN KEY,
);

CREATE TABLE ACCESSORIO(
	COD_BARRE	NUMBER(13) PRIMARY KEY,
	NOME_ACC	VARCHAR2(20),
);

CREATE TABLE CONTIENE(
	COD_FORNITURA	NUMBER(10) FOREIGN KEY,
	COD_BARRE		NUMBER(13) FOREIGN KEY,
);

CREATE TABLE FORNITURA(
	COD_FORNITURA		NUMBER(10) PRIMARY KEY,
	DATA_SPEDIZIONE		DATE,
	PREZZO				NUMBER(19,4),
	P_IVA_FORN			NUMBER(11) FOREIGN KEY,
);

CREATE TABLE FORNITORE(
	P_IVA_FORN 			NUMBER(11) PRIMARY KEY,
	DENOMINAZIONE		VARCHAR2(20),
	TELEFONO			NUMBER(10),
	CF_FORNITORE		VARCHAR2(16),
);

CREATE TABLE VENDUTO(
	CF_CLIENTE	VARCHAR2(16) FOREIGN KEY,
	COD_BARRE	NUMBER(13)	FOREIGN KEY,
);

CREATE TABLE CLIENTE(
	CF_CLIENTE		VARCHAR2(16) PRIMARY KEY,
	NOME			VARCHAR2(20),
	COGNOME			VARCHAR2(20),
	CAP				NUMBER(5),
	DATA_NASCITA	DATE,
	VIA				VARCHAR2(40),
	CITTA			VARCHAR2(20),
);