-- RIPULISCE DB
DROP TABLE COMMISSARIATO CASCADE CONSTRAINTS;
DROP TABLE PERSONA CASCADE CONSTRAINTS;
DROP TABLE ACCESSORIO CASCADE CONSTRAINTS;
DROP TABLE FORNITORE CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE DIPENDENTE CASCADE CONSTRAINTS;
DROP TABLE TURNI_PROGRAMMATI CASCADE CONSTRAINTS;
DROP TABLE TURNI_EFFETTUATI CASCADE CONSTRAINTS;
DROP TABLE VENDITA CASCADE CONSTRAINTS;
DROP TABLE FORNITURA CASCADE CONSTRAINTS;
DROP TABLE EQUIPAGGIAMENTO CASCADE CONSTRAINTS;
DROP TABLE ARMA CASCADE CONSTRAINTS;
DROP TABLE MUNIZIONI CASCADE CONSTRAINTS;
DROP TABLE DENUNCIA CASCADE CONSTRAINTS;
DROP TABLE CONTIENE CASCADE CONSTRAINTS;
DROP TABLE VENDUTO CASCADE CONSTRAINTS;
DROP TABLE COMPRENDE CASCADE CONSTRAINTS;

-- CREAZIONE TABELLE
CREATE TABLE COMMISSARIATO(
	PEC					VARCHAR2(100) PRIMARY KEY,
	NOME_COMM			VARCHAR2(80) NOT NULL,
	CAP_COMM			NUMBER(5) NOT NULL,
	VIA_COMM			VARCHAR(100),
	CITTA_COMM			VARCHAR(40) NOT NULL
);

CREATE TABLE PERSONA(
	CF							VARCHAR2(16) PRIMARY KEY,
	NOME						VARCHAR2(20) NOT NULL,
	COGNOME						VARCHAR2(20) NOT NULL,
	DATA_NASCITA				DATE NOT NULL,
	VIA							VARCHAR2(50) NOT NULL,
	CAP							NUMBER(5) NOT NULL,
	CITTA						VARCHAR2(40) NOT NULL,
	CONSTRAINT CF_AMMESSO 		CHECK (REGEXP_LIKE(CF, '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'))
);

CREATE TABLE ACCESSORIO(
	COD_BARRE					VARCHAR2(13) PRIMARY KEY,
	NOME_ACC					VARCHAR2(50)
);

CREATE TABLE FORNITORE(
	P_IVA_FORN 					VARCHAR2(11) PRIMARY KEY,
	DENOMINAZIONE				VARCHAR2(100),
	TELEFONO_FORN				VARCHAR2(10)
);

CREATE TABLE CLIENTE(
	NUM_PORTO_ARMI				VARCHAR2(8) PRIMARY KEY,
	CF_CLI						VARCHAR2(16) NOT NULL,
	TELEFONO					VARCHAR2(10),
	CONSTRAINTS	FK_CF_CLI		FOREIGN KEY (CF_CLI)			REFERENCES PERSONA(CF) ON DELETE CASCADE,
	CONSTRAINTS FORMATO_P_ARMI	CHECK (REGEXP_LIKE(NUM_PORTO_ARMI, '^[0-9]{5}-[A-Z]$'))
);

CREATE TABLE DIPENDENTE(
	NUM_TESSERINO				VARCHAR2(10) PRIMARY KEY,
	CF_DIP						VARCHAR2(16) NOT NULL,
	CONSTRAINTS	FK_CF_DIP 		FOREIGN KEY (CF_DIP) 			REFERENCES PERSONA(CF) ON DELETE CASCADE
);

CREATE TABLE TURNI_PROGRAMMATI(
	DATA_TP						DATE,
	ORA_TP						VARCHAR2(5),
	NUM_TESSERINO				VARCHAR2(10) NOT NULL,
	CONSTRAINTS PK_TP 			PRIMARY KEY (DATA_TP,ORA_TP),
	CONSTRAINTS FK_NUM_TES1 	FOREIGN KEY (NUM_TESSERINO)		REFERENCES DIPENDENTE(NUM_TESSERINO) ON DELETE CASCADE,
	CONSTRAINTS FORMATO_ORA_TP	CHECK (REGEXP_LIKE(ORA_TP, '^(0[0-9]|1[0-9]|2[0-3]|[0-9]):[0-5][0-9]$'))
);

CREATE TABLE TURNI_EFFETTUATI(
	DATA_TE						DATE,
	ORA_TE						VARCHAR2(5),
	NUM_TESSERINO				VARCHAR2(10) NOT NULL,
	CONSTRAINTS PK_TE 			PRIMARY KEY (DATA_TE,ORA_TE),
	CONSTRAINTS FK_NUM_TES2 	FOREIGN KEY (NUM_TESSERINO)		REFERENCES DIPENDENTE(NUM_TESSERINO) ON DELETE CASCADE,
	CONSTRAINTS FORMATO_ORA_TE	CHECK (REGEXP_LIKE(ORA_TE, '^(0[0-9]|1[0-9]|2[0-3]|[0-9]):[0-5][0-9]$'))
);

CREATE TABLE VENDITA(
	NUM_PROG					VARCHAR2(10) PRIMARY KEY,
	DATA_V						DATE NOT NULL,
	ORA_V						VARCHAR2(5) NOT NULL,
	IMPORTO						NUMBER(19,4),
	NUM_TESSERINO				VARCHAR2(10),
	CONSTRAINTS FK_NUM_TES3		FOREIGN KEY (NUM_TESSERINO) 	REFERENCES DIPENDENTE(NUM_TESSERINO) ON DELETE SET NULL,
	CONSTRAINTS FORMATO_ORA_V	CHECK (REGEXP_LIKE(ORA_V, '^(0[0-9]|1[0-9]|2[0-3]|[0-9]):[0-5][0-9]$'))
);

CREATE TABLE FORNITURA(
	COD_FORNITURA				VARCHAR2(10) PRIMARY KEY,
	DATA_SPEDIZIONE				DATE NOT NULL,
	PREZZO_LOTTO				NUMBER(19,4) NOT NULL,
	P_IVA_FORN					VARCHAR2(11),
	CONSTRAINTS FK_P_IVA_FORN 	FOREIGN KEY (P_IVA_FORN)		REFERENCES FORNITORE(P_IVA_FORN) ON DELETE CASCADE
);

CREATE TABLE EQUIPAGGIAMENTO(
	CODICE_PRODOTTO				VARCHAR2(10) PRIMARY KEY,
	CALIBRO						NUMBER(2) NOT NULL,
	MARCA						VARCHAR2(20),
	COD_FORNITURA				VARCHAR2(10) NOT NULL,
	NUM_PORTO_ARMI				VARCHAR2(8),
	NUM_PROG					VARCHAR2(10),
	CONSTRAINTS FK_COD_FOR1 	FOREIGN KEY (COD_FORNITURA)		REFERENCES FORNITURA(COD_FORNITURA) ON DELETE CASCADE,
	CONSTRAINTS FK_NUM_POR_ARM	FOREIGN KEY (NUM_PORTO_ARMI)	REFERENCES CLIENTE(NUM_PORTO_ARMI) ON DELETE SET NULL,
	CONSTRAINTS FK_NUM_PROG1	FOREIGN KEY (NUM_PROG)			REFERENCES VENDITA(NUM_PROG) ON DELETE SET NULL
);

CREATE TABLE ARMA(
	MATRICOLA					VARCHAR2(7) PRIMARY KEY,
	MODELLO 					VARCHAR2(50),
	CODICE_PRODOTTO				VARCHAR2(10) NOT NULL,
	CONSTRAINTS FK_COD_PR1		FOREIGN KEY (CODICE_PRODOTTO)	REFERENCES EQUIPAGGIAMENTO(CODICE_PRODOTTO) ON DELETE CASCADE
);

CREATE TABLE MUNIZIONI(
	NUM_LOTTO					VARCHAR2(10) PRIMARY KEY,
	CODICE_PRODOTTO				VARCHAR2(10) NOT NULL,
	CONSTRAINTS FK_COD_PR2		FOREIGN KEY (CODICE_PRODOTTO)	REFERENCES EQUIPAGGIAMENTO(CODICE_PRODOTTO) ON DELETE CASCADE
);

CREATE TABLE DENUNCIA(
	CODICE_PROGRESSIVO			VARCHAR2(10) PRIMARY KEY,
	DATA_DENUNCIA				DATE NOT NULL,
	PEC							VARCHAR2(100),
	CF							VARCHAR2(16) NOT NULL,
	CODICE_PRODOTTO				VARCHAR2(10) NOT NULL,
	CONSTRAINTS FK_PEC			FOREIGN KEY (PEC)				REFERENCES COMMISSARIATO(PEC) ON DELETE SET NULL,
	CONSTRAINTS FK_CF1			FOREIGN KEY (CF)				REFERENCES PERSONA(CF) ON DELETE CASCADE,
	CONSTRAINTS FK_CP1			FOREIGN KEY (CODICE_PRODOTTO)	REFERENCES EQUIPAGGIAMENTO(CODICE_PRODOTTO) ON DELETE CASCADE
);

CREATE TABLE CONTIENE(
	COD_FORNITURA				VARCHAR2(10),
	COD_BARRE_ACC				VARCHAR2(13),
	CONSTRAINTS PK_CON			PRIMARY KEY (COD_FORNITURA,COD_BARRE_ACC),
	CONSTRAINTS FK_COD_FOR2		FOREIGN KEY (COD_FORNITURA)		REFERENCES FORNITURA(COD_FORNITURA) ON DELETE CASCADE,
	CONSTRAINTS FK_COD_B1		FOREIGN KEY (COD_BARRE_ACC) 	REFERENCES ACCESSORIO(COD_BARRE) ON DELETE CASCADE
);

CREATE TABLE VENDUTO(
	CF_PERSONA					VARCHAR2(16),
	COD_BARRE_ACC				VARCHAR2(13),
	CONSTRAINTS PK_VEN			PRIMARY KEY (CF_PERSONA,COD_BARRE_ACC),
	CONSTRAINTS FK_CF2			FOREIGN KEY (CF_PERSONA) 		REFERENCES PERSONA(CF) ON DELETE CASCADE,
	CONSTRAINTS FK_COD_B2		FOREIGN KEY (COD_BARRE_ACC)		REFERENCES ACCESSORIO(COD_BARRE) ON DELETE CASCADE
);

CREATE TABLE COMPRENDE(
	NUM_PROG					VARCHAR2(10),
	COD_BARRE_ACC				VARCHAR2(13),
	CONSTRAINTS PK_COM			PRIMARY KEY (NUM_PROG,COD_BARRE_ACC),
	CONSTRAINTS FK_NUM_PROG2	FOREIGN KEY (NUM_PROG)			REFERENCES VENDITA(NUM_PROG) ON DELETE CASCADE,
	CONSTRAINTS FK_COD_B3		FOREIGN KEY (COD_BARRE_ACC)		REFERENCES ACCESSORIO(COD_BARRE) ON DELETE CASCADE
);