CREATE OR REPLACE PROCEDURE AcquistaNuovoCliente (
	NUM_T		IN VARCHAR2,	-- NUMERO DEL TESSERINO DEL DIPENDENTE
	COD_PR		IN VARCHAR2,	-- CODICE PRODOTTO EQUIPAGGIAMENTO
	PREZZO		IN NUMBER,		-- IMPORTO DELLA VENDITA
	-- GENERALITA' DEL NUOVO CLIENTE
	CF_C		IN VARCHAR2,	-- CODICE FISCALE DEL CLIENTE
	NOME_C		IN VARCHAR2,	-- NOME DEL CLIENTE
	COGN_C		IN VARCHAR2,	-- COGNOME DEL CLIENTE
	DN_C		IN DATE,		-- DATA DI NASCITA DEL CLIENTE
	VIA_C		IN VARCHAR2,	-- VIA DEL CLIENTE
	CAP_C		IN VARCHAR2,	-- CAP DEL CLIENTE
	CITTA_C		IN VARCHAR2,	-- CITTA DEL CLIENTE
	NPA_C		IN VARCHAR2,	-- NUMERO PORTO D'ARMI DEL CLIENTE
	TEL_C		IN VARCHAR2		-- NUMERO DI TELEFONO DEL CLIENTE
	)
AS
	TMP			NUMBER(1);		-- VARIABILE TEMPORANEA
	NUM_P		VARCHAR2(10);	-- NUMERO PROGRESSIVO VENDITA <PK>
	NPA			VARCHAR2(7);	-- NUMERO PORTO D'ARMI DEL CLIENTE
	ISCLIENTE	EXCEPTION;
	COMPRATA	EXCEPTION;
BEGIN
	-- GENERA NUMERO PROGRESSIVO VENDITA
	LOOP
		-- QUESTO CICLO ASSICURA L'UNIVOCITA' DEL NUMERO PROGRESSIVO
		NUM_P := SUBSTR(TO_CHAR(DBMS_RANDOM.VALUE(1111111111,999999999)),1,10);
		SELECT COUNT(*) INTO TMP
		FROM VENDITA
		WHERE NUM_PROG = NUM_P;
		EXIT WHEN TMP = 0;
	END LOOP;
	
	-- VERIFICA CHE L'ACQUIRENTE NON SIA GIA' UN CLIENTE DELL'ARMERIA
	SELECT COUNT(CF_CLI) INTO TMP
	FROM CLIENTE
	WHERE CF_CLI = CF_C;
	IF TMP = 0 THEN
		-- INSERISCE IL NUOVO CLIENTE NELLA BASE DI DATI
		INSERT INTO PERSONA (CF, NOME, COGNOME, DATA_NASCITA, VIA, CAP, CITTA)
		VALUES (CF_C, NOME_C, COGN_C, TO_DATE(DN_C,'DD-MON-YY'), VIA_C, CAP_C, CITTA_C);
		INSERT INTO CLIENTE (NUM_PORTO_ARMI, CF_CLI, TELEFONO)
		VALUES (NPA_C, CF_C, TEL_C);
	ELSE
		RAISE ISCLIENTE;
	END IF;
	
	-- VERIFICA CHE IL PRODOTTO NON SIA STATA GIA' ACQUISTATO
	SELECT COUNT(NUM_PORTO_ARMI) INTO TMP
	FROM EQUIPAGGIAMENTO
	WHERE CODICE_PRODOTTO = COD_PR;
	IF TMP = 0 THEN
		-- INSERISCE UNA VENDITA "GENERA SCONTRINO"
		INSERT INTO VENDITA (NUM_PROG,DATA_V,ORA_V,IMPORTO,NUM_TESSERINO) 
		VALUES (NUM_P, TO_DATE(SYSDATE,'DD-MON-YY'), TO_CHAR(SYSTIMESTAMP,'HH24:MI'), PREZZO, NUM_T);
		
		-- AGGIORNA LO STATO DELL'ARMA (NUOVO PROPRIETARIO)
		UPDATE EQUIPAGGIAMENTO
		SET NUM_PROG = NUM_P, NUM_PORTO_ARMI = NPA
		WHERE CODICE_PRODOTTO = COD_PR;
	ELSE
		RAISE COMPRATA;
	END IF;
	
EXCEPTION
	WHEN ISCLIENTE THEN
		RAISE_APPLICATION_ERROR(-20012, 'IL CLIENTE E GIA PRESENTE IN BANCA DATI');
	WHEN COMPRATA THEN
		RAISE_APPLICATION_ERROR(-20010, 'PRODOTTO GIA ACQUISTATO');
END;
/