CREATE OR REPLACE PROCEDURE InfoArma (
	MATRIC				VARCHAR2
	)
AS
	TMP					NUMBER(1);		-- VARIABILE TEMPORANEA
	MODEL				VARCHAR2(50);	-- MODELLO DELL'ARMA
	COMMISS				VARCHAR2(80);	-- COMMISSARIATO DELL'EVENTUALE DENUNCIA
	DATA_DEN			DATE;			-- DATA DELL'EVENTUALE DENUNCIA
	NOME_C				VARCHAR2(20);	-- NOME DELL'EVENTUALE CLIENTE
	COGN_C				VARCHAR2(20);	-- COGNOME DELL'EVENTUALE CLIENTE
	NPA_C				VARCHAR2(8);	-- PORTO D'ARMI DELL'EVENTUALE CLIENTE
	NUM_P				VARCHAR2(10);	-- NOMERO PROGRESSIVO DELL'EVENTUALE VENDITA
	ARMA_NOT_EXISTS		EXCEPTION;
BEGIN
	-- VERIFICA SE L'ARMA ESISTE
	SELECT COUNT(*) INTO TMP
	FROM ARMA
	WHERE MATRICOLA = MATRIC;
	IF TMP = 0 THEN
		RAISE ARMA_NOT_EXISTS;
	END IF;
	DBMS_OUTPUT.PUT_LINE('--INFORMAZIONI ARMA--');
	
	-- LEGGE MODELLO ARMA
	SELECT MODELLO INTO MODEL
	FROM ARMA
	WHERE MATRICOLA = MATRIC;
	DBMS_OUTPUT.PUT_LINE('Modello arma: '||MODEL);
	DBMS_OUTPUT.PUT_LINE('Matricola: '||MATRIC);
	
	-- VERIFICA CHE L'ARMA SIA STATA GIA COMPRATA
	SELECT NUM_PROG INTO NUM_P
	FROM EQUIPAGGIAMENTO E
	JOIN ARMA A
	ON E.CODICE_PRODOTTO = A.CODICE_PRODOTTO
	WHERE MATRICOLA = MATRIC;
	
	-- LEGGE L'EVENTUALE PROPRIETARIO
	IF NUM_P IS NOT NULL THEN
		-- LEGGE IL NOME DEL PROPRIETARIO
		SELECT NOME INTO NOME_C
		FROM ARMA A
		JOIN EQUIPAGGIAMENTO E
		ON A.CODICE_PRODOTTO = E.CODICE_PRODOTTO
		JOIN CLIENTE C
		ON E.NUM_PORTO_ARMI = C.NUM_PORTO_ARMI
		JOIN PERSONA P
		ON C.CF_CLI = P.CF
		WHERE MATRICOLA = MATRIC;
		
		-- LEGGE IL COGNOME DEL PROPRIETARIO
		SELECT COGNOME INTO COGN_C
		FROM ARMA A
		JOIN EQUIPAGGIAMENTO E
		ON A.CODICE_PRODOTTO = E.CODICE_PRODOTTO
		JOIN CLIENTE C
		ON E.NUM_PORTO_ARMI = C.NUM_PORTO_ARMI
		JOIN PERSONA P
		ON C.CF_CLI = P.CF
		WHERE MATRICOLA = MATRIC;
		DBMS_OUTPUT.PUT_LINE('Detentore: '||NOME_C||' '||COGN_C);
		
		-- LEGGE IL PORTO D'ARMI DEL PROPRIETARIO
		SELECT C.NUM_PORTO_ARMI INTO NPA_C
		FROM ARMA A
		JOIN EQUIPAGGIAMENTO E
		ON A.CODICE_PRODOTTO = E.CODICE_PRODOTTO
		JOIN CLIENTE C
		ON E.NUM_PORTO_ARMI = C.NUM_PORTO_ARMI
		JOIN PERSONA P
		ON C.CF_CLI = P.CF
		WHERE MATRICOLA = MATRIC;
		DBMS_OUTPUT.PUT_LINE('Porto d''armi: '||NPA_C);
		
		-- VERIFICA SE L'ARMA E' STATA DENUNCIATA
		SELECT COUNT(*) INTO TMP
		FROM DENUNCIA D
		JOIN EQUIPAGGIAMENTO E
		ON D.CODICE_PRODOTTO = E.CODICE_PRODOTTO
		JOIN ARMA A
		ON E.CODICE_PRODOTTO = A.CODICE_PRODOTTO
		WHERE MATRICOLA = MATRIC;
		
		IF TMP <> 0 THEN 
			-- LEGGE IL COMMISSARIATO
			SELECT NOME_COMM INTO COMMISS
			FROM ARMA A
			JOIN EQUIPAGGIAMENTO E
			ON A.CODICE_PRODOTTO = E.CODICE_PRODOTTO
			JOIN DENUNCIA D
			ON E.CODICE_PRODOTTO = D.CODICE_PRODOTTO
			JOIN COMMISSARIATO C
			ON D.PEC = C.PEC
			WHERE MATRICOLA = MATRIC;
			
			-- LEGGE LA DATA DELLA DENUNCIA
			SELECT DATA_DENUNCIA INTO DATA_DEN
			FROM DENUNCIA D
			JOIN EQUIPAGGIAMENTO E
			ON D.CODICE_PRODOTTO = E.CODICE_PRODOTTO
			JOIN ARMA A
			ON E.CODICE_PRODOTTO = A.CODICE_PRODOTTO
			WHERE MATRICOLA = MATRIC;
			DBMS_OUTPUT.PUT_LINE('Denunciata il '||DATA_DEN||' presso il '||COMMISS);
		ELSE
			DBMS_OUTPUT.PUT_LINE('L''arma non e'' stata ancora denunciata.');
		END IF;
	END IF;
	
EXCEPTION
	WHEN ARMA_NOT_EXISTS THEN
		RAISE_APPLICATION_ERROR(-20095, 'Arma non disponibile nella banca dati');
END;
/