CREATE OR REPLACE TRIGGER ETA_MAGG
BEFORE INSERT ON PERSONA
FOR EACH ROW
DECLARE
	MINORENNE	EXCEPTION;
BEGIN
	IF FLOOR(MONTHS_BETWEEN(SYSDATE,:NEW.DATA_NASCITA) / 12) < 18 THEN
		RAISE MINORENNE;
	END IF;
EXCEPTION
	WHEN MINORENNE THEN
		RAISE_APPLICATION_ERROR(-20001,'Persona non maggiorenne');
END;
/