CREATE OR REPLACE TRIGGER IMP_MAX
BEFORE INSERT ON FORNITURA
FOR EACH ROW
DECLARE
	TRP_PREZZO	EXCEPTION;
BEGIN
	IF :NEW.PREZZO_LOTTO > 15000 THEN
		RAISE TRP_PREZZO;
	END IF;
EXCEPTION
	WHEN TRP_PREZZO THEN
		RAISE_APPLICATION_ERROR(-20002, 'Importo fornitura troppo alto');
END;
/