CREATE OR REPLACE TRIGGER ORA_MAGGTE
BEFORE INSERT ON TURNI_EFFETTUATI
FOR EACH ROW
DECLARE
	ORARIO	EXCEPTION;
BEGIN
	IF :NEW.ORA_TE>'21:00' OR :NEW.ORA_TE<'07:30'  THEN
		RAISE ORARIO;
	END IF;
EXCEPTION
	WHEN ORARIO THEN
		RAISE_APPLICATION_ERROR(-20004,'Armeria Chiusa');
END;
/