CREATE OR REPLACE TRIGGER TROPPE_DENUNCE
BEFORE INSERT ON DENUNCIA
FOR EACH ROW
DECLARE
	DENUNCE		EXCEPTION;
	CONTATORE	 NUMBER;
BEGIN

	SELECT COUNT(*) INTO CONTATORE
	FROM DENUNCIA
	WHERE DATA_DENUNCIA = :NEW.DATA_DENUNCIA;
	IF CONTATORE > 15 THEN
		RAISE DENUNCE;
	END IF;
EXCEPTION
	WHEN DENUNCE THEN
		RAISE_APPLICATION_ERROR(-20006,'Non si possono gestire piu di 15 denunce in un giorno');
END;
/